apiVersion: v1
kind: Service
metadata:
    name: "orderfinal-3186"
    labels:
        app: "orderfinal-3186"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "orderfinal-3186"